# Default username for each of the machines listed below
username: "professor"

# List of machines where the LTSP solution is installed,
# so that we can install/remove softwares to be replicated the other workstations on the lab.
machines: 
  - labname: "LabMatica"
    ip: "10.100.64.34"
  - labname: "Labin 2"
    ip: "999.999.999.999"